### ISSUE TITLE
Manually Importing findbugs-result.xml to sonar-cube

### ISSUE THREAD

**Issue by rkamath3** [SonarQubeCommunity/sonar-findbugs#100]
Hello,

If I have a findbugs-result.xml how can I push it to sonar-cube? Are there any web service which accepts the report and displays it on the dashboard ?

Regards
Ram

**Comment by candicelinyi** [comment]
In the navigation, you can find "Quality Profiles", click it, then click "create" on the right corner of the page, then select language as "Java", you will see a "Choose File" button for findBugs.

**Comment by rkamath3** [comment]
Hello

Thanks for the reply. Above mentioned solution is to upload a configuration. However, I donot want to upload a configuration but the result itself. I have a bug report which I would like to publish on sonar-cube. So that it can appear on the dashboard.

Best Regards
Ram

**Comment by h3xstream** [comment]
Sorry this is not possible. The analysis need to be ran by the Sonar-FindBugs plugin.

**Comment by h3xstream** [comment]
@rkamath3 Where is located your findbugs report ?

I'm considering skipping scan if `target/findbugsXml.xml` is present. This would allow the reuse of existing scan + support of more complex configuration.
