### ISSUE TITLE
finbugs version that contains findsecbugs 1.6.0?

### ISSUE THREAD

**Issue by javixeneize** [SonarQubeCommunity/sonar-findbugs#101]
Hi

After reading #88 and #97 this is still unclear for me

Doc page says that the latest sonar findbugs version is 3.5 which contains findsecbugs 1.5.0

What is the findbugs version that contains findsecbugs 1.6.0? Has it been released yet?

Thanks

**Comment by marschall** [comment]
Findbugs itself does not contain findsecbugs. But the sonar-plugin does include findsecbugs. findsecbus 1.6.0 is included in the current -SNAPSHOT version of the development branch. See also #99.

**Comment by javixeneize** [comment]
Thanks. Reading that (https://github.com/find-sec-bugs/find-sec-bugs/wiki/Sonar-Qube-Tutorial) i understood it was included

Can you advise how to download the .jar for findsecbugs and how to install in Sonar, as it is not in the update page? I assume it will be copy&paste in the plugin folder, but just in case

Can you also confirm sonar version compatibility? Does it work with Sonar 5.6?

Thanks

**Comment by marschall** [comment]
Disclaimer: I'm not part of the project nor do I speak for the project.

If you can wait for a 3.4.5 or 3.5 release of the plugin I would wait for that release. If that is not an option I'm torn between manually editing the JAR file or building from master.

We're currently using version 3.4.4 of the plugin in SonarQube 5.6 and I would expect versions 3.4.5/3.5 to work as well.

**Comment by javixeneize** [comment]
Yes, i can wait, not in a rush

Any idea when that new release will be ready?

Thanks

**Comment by marschall** [comment]
Nope, sorry.

**Comment by h3xstream** [comment]
Release is coming..
