### ISSUE TITLE
Scala Quality Profile (SQ 6.4, 6.3.1, 6.3)

### ISSUE THREAD

**Issue by Thg-vinod-anandan** [SonarQubeCommunity/sonar-findbugs#108]
Dear Philip,

Thank you very much for the Find-Sec-Bugs Sonarqube plugin. It's a really valuable plugin to improve the security of applications.

I have tried the latest version of the plugin (3.5.0) with Sonarqube 6.3, 6.3.1, 6.4 however, I couldn't find the Scala quality profiles in the SonarQube.

Since 6.3, I believe SonarQube will allow the plugins to access any file extension. https://jira.sonarsource.com/browse/MMF-145

Could you please let me know, what are the changes needed to enable the Scala quality profiles as well as to get these scanned by the plugin?

Thank you,

Vinod

**Comment by h3xstream** [comment]
Their are plenty of limitation with the SonarQube architecture regarding the multi-language support.
It is closely tie to the sonar-source plugin design.

 - Language can't have the same extension (https://jira.sonarsource.com/browse/MMF-672)
 - Repository can't contains rule that apply to multiple languages. (If you would have Scala only code, the Java core rules would not be enable unless you have one Java file present)
 - Sensor are couple to the language definition (depends on the most popular plugin that declares it).
 - etc, etc..

I will be evaluating the integration with Jenkins soon. The design would allow the support of other languages.

**Comment by h3xstream** [comment]
Related #28 (Will not be possible on short term)
