### ISSUE TITLE
Findbugs equivalent for node js

### ISSUE THREAD

**Issue by javixeneize** [SonarQubeCommunity/sonar-findbugs#116]
Hi

Is there any plugin for sonar that contains security rules for nodejs?

Thanks

**Comment by h3xstream** [comment]
The best place to ask this question would be the community forum : https://groups.google.com/forum/#!forum/sonarqube

I am not well place to recommend any static analysis tool for NodeJS.  [awesome-static-analysis](https://github.com/mre/awesome-static-analysis#javascript) can be a place to start.. That's just my 2¢.
