### ISSUE TITLE
Incompatible BCEL version

### ISSUE THREAD

**Issue by volphy** [SonarQubeCommunity/sonar-findbugs#121]
There is a known issue with BCEL in fb-contrib:
https://github.com/mebigfatguy/fb-contrib/issues/205

It has already been fixed in fb-contrib 7.0.3

sonar-findbugs seems to be using fb-contrib 7.0.0

Are there any plans to migrate to fb-contrib 7.0.3 in near future?

**Comment by h3xstream** [comment]
#122 was merged

**Comment by wilx** [comment]
I am seeing this with SonarQube 5.6.6 and Findbugs 3.5 installed. Is there a workaround for this?
 
```
00:06:09 The following errors occurred during analysis:
00:06:27   Exception analyzing com.ca.tas.resman.parser.FilterParser using detector com.mebigfatguy.fbcontrib.detect.OverlyPermissiveMethod
00:06:27     java.lang.RuntimeException: Incompatible bcel version
00:06:27       At com.mebigfatguy.fbcontrib.detect.OverlyPermissiveMethod.getBootstrapMethod(OverlyPermissiveMethod.java:379)
```

**Comment by durandx** [comment]
This bug is **blocking** builds. 
What is the workaround ? When this bug will be release ? How to revert to the previous version ?

**Comment by h3xstream** [comment]
@durandx It will come with the next release of Sonar-FindBugs.

**Comment by tunovic** [comment]
We do experience the same issue. When will the version 3.6 be released?

**Comment by VinodAnandan** [comment]
It's just been released, you can download it from here.

https://github.com/SonarQubeCommunity/sonar-findbugs/releases/tag/3.6.0

**Comment by tunovic** [comment]
Thanks.
