### ISSUE TITLE
Update 3rd party plugins

### ISSUE THREAD

**Issue by h3xstream** [SonarQubeCommunity/sonar-findbugs#125]
FindSecurityBugs 1.7.1
FB-contrib 7.0.3-sb

**Comment by h3xstream** [comment]
@Vampire If you are looking for quick patch release would #124 be acceptable for you?
(launching findbugs/spotbugs prior the Sonar command)

**Comment by Vampire** [comment]
@h3xstream I guess not, as the bug I mention is not even fixed yet. Regarding the general approach of #124, I'm not sure. Would simply analyzing with a different version work? Don't you have to provide SQ information about the rules? Also when running in "issues" mode, only files different from last analysis are analysed. And which rules are to be checked would not be configurable in SQ server anymore, ... :-/
I guess I would prefer to wait for a fixed version or build it myself and just live with a couple of issues missed until then.

**Comment by h3xstream** [comment]
The update now include the newer version. https://github.com/SonarQubeCommunity/sonar-findbugs/releases/tag/3.6.0
