### ISSUE TITLE
SonarQube and Findbugs compatibility Query

### ISSUE THREAD

**Issue by tarun008** [SonarQubeCommunity/sonar-findbugs#134]
[SonarQube and Findbugs compatibility Query.docx](https://github.com/SonarQubeCommunity/sonar-findbugs/files/1295078/SonarQube.and.Findbugs.compatibility.Query.docx)

**Comment by h3xstream** [comment]
@tarun008 Please use Github description rather than uploading docx.

**Comment by tarun008** [comment]
I have noticed that Findbugs and SonarQube Compatibility is not very clear.

As per following page, Findbugs 3.5 is compatible with SonarQube 5.6 which could either mean all 5.6.x minor releases or only the latest minor release.
https://docs.sonarqube.org/display/PLUG/Plugin+Version+Matrix

There are 6 minor LTS release versions of SonarQube 5.6.
I am using SonarQube 5.6.4. and as per SonarQube update center, it requires “System Update” to upgrade Findbugs to 3.5 but we are not sure which minimum version of SonarQube we need to upgrade to?

Q1. Could you please confirm which is the minimum version of SonarQube supported by sonar-findbugs 3.5?
Q2. Is sonar-findbugs 3.5 released for production? It shows as “Pre-release” in following page https://github.com/SonarQubeCommunity/sonar-findbugs/releases/tag/3.5.0?

Thanks.

**Comment by h3xstream** [comment]
Yes 3.5 is release. The pre-release tag was left by accident. It should work on the latest version of 5.6.
When doing integration tests, I use the latest version of 5.6 and 6.4 available.
