### ISSUE TITLE
fingbuds throw exception if only java file exist

### ISSUE THREAD

**Issue by koetheq** [SonarQubeCommunity/sonar-findbugs#136]
Before install fingbugs plugin, the SonarWay can scan java file if no class file available.  But after installed findbugs plug-in, it will throws an exception.  I think, if Findbugs cannot scan java only files, it should not throws exception, to allow other java scan tools like sonar way to continue to scan, not just throw an exception

**Comment by h3xstream** [comment]
The exception is there to avoid placebo effect. Compiling code is mandatory for FindBugs and some analyzer from Sonar-Squid.
If you insist on not compiling your code, don't use findbugs. (Use a different quality profile.)

I still highly recommend you to compile your code to see the difference between Sonar analyzer and FindBugs/SpotBugs.
