### ISSUE TITLE
Findbugs execution: Invalid classfile format in module-info.class. Java 9 support

### ISSUE THREAD

**Issue by pethers** [SonarQubeCommunity/sonar-findbugs#139]
Using version 3.6.0

Get error in 
https://www.hack23.com/jenkins/job/Citizen-Intelligence-Agency-Complete-site-sonar-report/2937/console

```
Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.3.0.603:sonar (default-cli) on project parent-pom: Can not execute Findbugs: java.lang.RuntimeException: java.io.IOException: IOException while scanning codebases: Invalid classfile format in /var/lib/jenkins/jobs/Citizen-Intelligence-Agency-Complete-site-sonar-report/workspace/service.api/target/classes/module-info.class
```

**Comment by h3xstream** [comment]
Looking at it.

**Comment by pethers** [comment]
Tried solving it in https://github.com/SonarQubeCommunity/sonar-findbugs/pull/140 , thought using ASM 6_BETA for sure would solve it but it didn't.

**Comment by h3xstream** [comment]
I'm not sure if Jigsaw is supported by SpotBugs.

**Comment by pethers** [comment]
Wish they add support for it soon, feel like hippie with just around 400 rules in sonarqube instead of 1200 + with sonar-findbugs included :)

**Comment by h3xstream** [comment]
I could temporally skip the addition of `module-info.class` since their are no rule at the moment that look at dependency in this class file.

**Comment by h3xstream** [comment]
Ideally SpotBugs should handle it .. temporally their will be this change #141

**Comment by h3xstream** [comment]
A new release is available : https://github.com/SonarQubeCommunity/sonar-findbugs/releases/tag/3.6.0

**Comment by pethers** [comment]
Excellent, testing it now :)

**Comment by pethers** [comment]
Thanks for all the help, it works to use the sonar-findbugs plugin now. Running at https://www.hack23.com/sonar/dashboard?id=com.hack23.cia%3Aparent-pom

**Comment by h3xstream** [comment]
The version 3.7.0 is available in a prerelease form : https://github.com/spotbugs/sonar-findbugs/releases/tag/3.7.0 (SonarQube GG https://groups.google.com/forum/#!topic/sonarqube/2DGGjoMfDSc)
