### ISSUE TITLE
False positive for "Correctness - Method uses Properties.put instead of Properties.setProperty"

### ISSUE THREAD

**Issue by richardgroote** [SonarQubeCommunity/sonar-findbugs#149]
In our project we have changed the `properties.put` to`properties.setProperty`.
But the below scenario still complains 

`permittedProperties.setProperty((String)property.getKey(), (String)property.getValue());`

**Comment by h3xstream** [comment]
You are probably referring to a SpotBugs detector.

The best place to report about the core SpotBugs rules would be:
https://github.com/spotbugs/spotbugs/issues
