### ISSUE TITLE
False positive XSS when using OWASP taglib

### ISSUE THREAD

**Issue by gvasquez-waypoint** [SonarQubeCommunity/sonar-findbugs#154]
Seems like the plugin (or perhaps FindBugs itself) is not considering the use of the taglib version of the [OWASP Encoder](https://www.owasp.org/index.php/OWASP_Java_Encoder_Project), as it is reporting a violation in the following excerpt:

`<br />MEDIANO PLAZO (${e:forHtmlContent(left)})<br />`

Considering:

`<%@taglib prefix="e" uri="https://www.owasp.org/index.php/OWASP_Java_Encoder_Project" %>
`

**Comment by h3xstream** [comment]
Please open an issue here : https://github.com/find-sec-bugs/find-sec-bugs/issues

**Comment by gvasquez-waypoint** [comment]
Done, created issue [353](https://github.com/find-sec-bugs/find-sec-bugs/issues/353)
