### ISSUE TITLE
Level of DWI_DELETING_WHILE_ITERATING

### ISSUE THREAD

**Issue by NPi2Loup** [SonarQubeCommunity/sonar-findbugs#20]
Shouldn't rule DWI_DELETING_WHILE_ITERATING be at higher level than INFO ?
It's clearly a bug, because it throw an Exception in almost all cases.

**Comment by h3xstream** [comment]
Hi @NPi2Loup,
I was thinking about putting Correctness bug to **MAJOR**. SonarQube levels are : INFO, MAJOR and CRITICAL.

What do you think?

**Comment by h3xstream** [comment]
Update in 6284bc20c72461637c5e25b2760c21e6e5291d5d

DWI_DELETING_WHILE_ITERATING was change from INFO to MAJOR.
https://github.com/SonarQubeCommunity/sonar-findbugs/blob/master/src/main/resources/org/sonar/plugins/findbugs/rules-fbcontrib.xml#L1369

**Comment by h3xstream** [comment]
If you want to validate the change, please test this release : https://github.com/SonarQubeCommunity/sonar-findbugs/releases/tag/3.4-SNAPSHOT
