### ISSUE TITLE
SonarQube 5.5 + Find bugs - latest version

### ISSUE THREAD

**Issue by aravindk47** [SonarQubeCommunity/sonar-findbugs#25]
04:35:07,020 WARN  - ERROR: Error during Sonar runner execution
04:35:07,021 WARN  - org.sonar.runner.impl.RunnerException: Unable to execute Sonar
04:35:07,021 WARN  - 	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:91)
04:35:07,021 WARN  - 	at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
04:35:07,021 WARN  - 	at java.security.AccessController.doPrivileged(Native Method)
04:35:07,021 WARN  - 	at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
04:35:07,021 WARN  - 	at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
04:35:07,021 WARN  - 	at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
04:35:07,021 WARN  - 	at org.sonar.runner.api.Runner.execute(Runner.java:100)
04:35:07,021 WARN  - 	at org.sonar.runner.Main.executeTask(Main.java:70)
04:35:07,021 WARN  - 	at org.sonar.runner.Main.execute(Main.java:59)
04:35:07,021 WARN  - 	at org.sonar.runner.Main.main(Main.java:53)
04:35:07,021 WARN  - Caused by: java.lang.NoSuchMethodError: org.sonar.api.resources.Project.getFileSystem()Lorg/sonar/api/resources/ProjectFileSystem;
04:35:07,021 WARN  - 	at org.sonar.plugins.findbugs.resource.ByteCodeResourceLocator.findJavaClassFile(ByteCodeResourceLocator.java:55)
04:35:07,021 WARN  - 	at org.sonar.plugins.findbugs.FindbugsSensor.analyse(FindbugsSensor.java:122)
04:35:07,021 WARN  - 	at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
04:35:07,021 WARN  - 	at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
04:35:07,021 WARN  - 	at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:83)
04:35:07,021 WARN  - 	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:189)
04:35:07,021 WARN  - 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
04:35:07,021 WARN  - 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
04:35:07,021 WARN  - 	at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:265)
04:35:07,022 WARN  - 	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:260)
04:35:07,022 WARN  - 	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:258)
04:35:07,022 WARN  - 	at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:250)
04:35:07,022 WARN  - 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
04:35:07,022 WARN  - 	at org.sonar.batch.scan.ProjectScanContainer.startComponents(ProjectScanContainer.java:128)
04:35:07,022 WARN  - 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
04:35:07,022 WARN  - 	at org.sonar.batch.task.ScanTask.execute(ScanTask.java:55)
04:35:07,022 WARN  - 	at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
04:35:07,022 WARN  - 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
04:35:07,022 WARN  - 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
04:35:07,022 WARN  - 	at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:124)
04:35:07,022 WARN  - 	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
04:35:07,022 WARN  - 	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:79)
04:35:07,022 WARN  - 	at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
04:35:07,022 WARN  - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
04:35:07,022 WARN  - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
04:35:07,022 WARN  - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
04:35:07,022 WARN  - 	at java.lang.reflect.Method.invoke(Method.java:606)
04:35:07,022 WARN  - 	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
04:35:07,022 WARN  - 	... 9 more

**Comment by h3xstream** [comment]
Known issue. SQ 5.6 include many refactoring / broken API.
I will try to provide a release candicate ASAP.

**Comment by h3xstream** [comment]
Hi @aravindk47,
You can test the latest version : https://github.com/SonarQubeCommunity/sonar-findbugs/releases/tag/3.4-SNAPSHOT
