### ISSUE TITLE
Configure the project to be analysed on SonarQube.com

### ISSUE THREAD

**Issue by bellingard** [SonarQubeCommunity/sonar-findbugs#31]
Hi @h3xstream 

I see that you're now the main maintainer of the Findbugs SQ plugin. You might (or might not) know that we've been analysing this project for quite some time already on SonarQube.com, the online SonarQube instance that is free for open-source project. You can see it live at https://sonarqube.com/overview?id=org.sonarsource.sonar-findbugs-plugin%3Asonar-findbugs-plugin

We are progressively moving the ownership of all the projects that are not ours to the original authors or the maintainers of the projects - so that you have the freedom to configure and run analysis the way you want. With this, you can also have analysis of pull requests.

Are you interested? If yes, then you can follow the procedure described at https://sonarqube.com/?did=157

Cheers

**Comment by h3xstream** [comment]
Yep I'm interested. I will look at it soon.

**Comment by h3xstream** [comment]
@bellingard  I have an account on sonarqube.com (link to my Github account).
I would like to configure the project settings.  Unfortunately, the link is now unavailable https://sonarqube.com/?did=157.

**Comment by bellingard** [comment]
@h3xstream I've granted you admin rights on the project, so it's now up to you to configure your CI to run analyses!

Enjoy!
