### ISSUE TITLE
FindBugs plugin should not start an analysis if no rules are enable

### ISSUE THREAD

**Issue by h3xstream** [SonarQubeCommunity/sonar-findbugs#37]
Ref : https://groups.google.com/d/msgid/sonarqube/8302d666-7751-4411-abe6-e6a9508f884a%40googlegroups.com

As described by Gilbert, the analysis should be skip no rules are enable. This would avoid the sanity check that force the compilation of the java code.

**Comment by znerd** [comment]
It appears this bug has re-appeared.

And it seems I'm not the only one that was hit by this, see a comment on #258 : 
> The reason we need a solution like this is because the profile rule detection is broken; it runs the spotbugs analyzer regardless of the rules in the profile

**Comment by xubella** [comment]
I also cross this issue , I want to disable findbugs when there is no findsbugs rules. does this issue resolved ?
