### ISSUE TITLE
findbugs-results.xml not imported to sonarqube

### ISSUE THREAD

**Issue by theatricshrink** [SonarQubeCommunity/sonar-findbugs#52]
Hi,

I have a sonarqube scanner setup in jenkins that analyzes my project. I have the findbugs plugin (3.4.3) installed in sonarqube (5.6.1). I'm using the quality profile "Findbugs" with most of the findbugs rules enabled and it's assigned to my project. I use a module based setup in my project (Project = TEST, module = toolbox, Jenkins workspace = SANITY; see screen).

![module](https://cloud.githubusercontent.com/assets/18421573/18384944/e1fda43a-768d-11e6-8a07-bea8af04ff4a.PNG)

SonarRunner states it uses the quality profile and also runs the findbugs scanner. It completes sucessfully and creates the findbugs-reports.xml file with several bug occurances:

e.g.
`<BugInstance instanceOccurrenceMax="0" instanceOccurrenceNum="0" instanceHash="39b5c792fb420506d326749965dca152" category="STYLE" abbrev="ST" rank="17" priority="2" type="ST_WRITE_TO_STATIC_FROM_INSTANCE_METHOD"><ShortMessage>Write to static field from instance method</ShortMessage><LongMessage>Write to static field com.reval.toolbox.CheckLogerr.ut_exetype from instance method ...`

I checked for that exact rule in my quality profile and it's enabled.

After the import completes none of the findings in the xml file is imported to sonarqube.

What could be the reason for that? I have some "could not be match to its original source file" in my scanner log but that should not prevent the whole report from being imported, right?

Thanks

![project](https://cloud.githubusercontent.com/assets/18421573/18384599/c5bafc84-768b-11e6-9ef2-140357d2d694.PNG)
![profile](https://cloud.githubusercontent.com/assets/18421573/18384601/c5bcaeee-768b-11e6-8909-322559c86c1a.PNG)

**Comment by h3xstream** [comment]
Good question
I am looking at this.

My first tough is maybe the priority (confidence) is too low.

**Comment by h3xstream** [comment]
By default, only the bug with priority medium or high are reported. This is because the average users tends to want as little False Positive as possible.

To report Low issues you can edit the priority setting in : **Project > Administration > Java > FindBugs > Confidence level**

![1](https://cloud.githubusercontent.com/assets/593130/18795573/299abe4e-8193-11e6-812d-198d2338e8ff.png)

=============================

According to your screenshot, the rule is probably enabled. You can also make sure to see that the rule was associate to the profile you used. The default profiles are sometimes broken with certain migrations.

![2](https://cloud.githubusercontent.com/assets/593130/18795577/3157c5be-8193-11e6-967c-de687a446ced.png)

**Comment by theatricshrink** [comment]
Thanks for the reply. I have now added the findbugs rules to the Sonar Way Quality Profile and enabled pretty much all of the rules. I checked in the findbugs findbugs-reports.xml and I also find violations with higher priority in there (like MS_SHOULD_BE_FINAL wich has priority 1). Still none of the violations are imported.
Something else i could check?

**Comment by h3xstream** [comment]
When you run the analysis (`mvn sonar:sonar` / `sonarRunner`), did you get any error / warning logged?

**Comment by theatricshrink** [comment]
I run the sonar runner from Jenkins. I get warnings logged regarding "The class '<classname>' could not be match to its original source file. It might be a dynamically generated class. No errors.

**Comment by theatricshrink** [comment]
I now updated the findbugs plugin from 3.4.3 to 3.4.4 and it seems to work now. No idea which of the fixes solved it. Thanks

**Comment by diaojunxian** [comment]
@h3xstream Hi,as I had run `java -jar $TOOLS/findbugs/lib/findbugs.jar -textui -xml -output findbugs-result.xml app`，and product one `findbugs-result.xml`，how can I use `soanr-runner`to upload the xml to sonar?
