### ISSUE TITLE
Update fb-contrib to v.6.8.0

### ISSUE THREAD

**Issue by kzaikin** [SonarQubeCommunity/sonar-findbugs#58]
Unfortunately no hyperlink to exact version so I copy release notes here:
http://fb-contrib.sourceforge.net

Detectors added in v6.8.0
[DMC] Dubious Map Collection
Looks for fields that are implementations of java.util.Map, but that are only ever iterated over. This probably means that this data structure should be a List of some class that holds two values, or at the least Pair. Map was probably choosen as it was the easiest thing to use, but obfuscates the reason for the data structure.
[BL] Burying Logic
Looks for relatively large if blocks of code, where you unconditionally return from them, and then follow that with an unconditional return of a small block. This places the bulk of the logic to the right indentation-wise, making it more difficult to read than needed. It would be better to invert the logic of the if block, and immediately return, allowing the bulk of the logic to be move to the left, for easier reading.
[WI] Wiring Issues
Looks for various issues around @Autowired/@Inject fields in DI classes
Injecting the same bean twice into the same class hierarchy, even with different field names
[CCI] Concurrent Collection Issues
Looks for various issues around using concurrent collections including
Using get/put with collection values, when you should use putIfAbsent

**Comment by h3xstream** [comment]
I close the issue too quickly. I need to regenerate the rules descriptions.

**Comment by kzaikin** [comment]
I have inspected previous version upgrades and was not able to see other changes but .pom. Could you share the required procedure please?

**Comment by kzaikin** [comment]
Aha! I can see BuildXmlFiles.groovy. Will check that today

**Comment by h3xstream** [comment]
@kzaikin Yes it generate the rule descriptions and profiles (for both plugin). It should work without any special configuration.
Thanks for the help

**Comment by kzaikin** [comment]
@h3xstream should we update README.md either?
Versions table does not have version 3.5 in it yet

**Comment by h3xstream** [comment]
@kzaikin  Added
