### ISSUE TITLE
Update plugin in Update Center

### ISSUE THREAD

**Issue by trulex** [SonarQubeCommunity/sonar-findbugs#64]
Latest version is 3.4.4, while Update Center has 3.4.3 version.

**Comment by h3xstream** [comment]
This is my fault. I did not follow carefully the [release thread](https://groups.google.com/forum/#!searchin/sonarqube/release$20sonar-findbugs%7Csort:relevance/sonarqube/m6Chu6M_NkM/idqdW0wPDQAJ).

**Comment by h3xstream** [comment]
It got lost in the queue again ..
I decided to ask again for a release of 3.4.4. https://groups.google.com/forum/#!topic/sonarqube/Qo-d4xFPxjI

**Comment by h3xstream** [comment]
It is now available.
