### ISSUE TITLE
Missing project name in "This project contains Java source files that are not compiled" error

### ISSUE THREAD

**Issue by szpak** [SonarQubeCommunity/sonar-findbugs#65]
Currently "This project contains Java source files that are not compiled" doesn't provide a name of a module which does not contain compiled sources. This can be problematic if you apply SonarQube plugin in Gradle on a module which contain multiple subproject. I was investigating this error in a project with ~20 submodules where (in the end) it turned out that one of the submodules wasn't add as a dependency to more generic one. Without project/module name it would be much easier to determine a source of problem.

I took a look into the code and unfortunately that information isn't available in FindbugsConfiguration directly. There is [`DefaultModuleFileSystem`](https://github.com/SonarSource/sonarqube/blob/master/sonar-scanner-engine/src/main/java/org/sonar/scanner/scan/filesystem/DefaultModuleFileSystem.java#L41) implementation of `FileSystem` which contains a module key, however FindBugs plugin doesn't know about it during compilation. A vanilla `FileSystem` instance doesn't have any identifier which can be used. Maybe it would be easier to pass another information (project/module name) to `FindbugsConfiguration` and later set it in edu.umd.cs.findbugs.Project as a name.

Somehow related to #56 and #46.

**Comment by h3xstream** [comment]
I could at least added the root path of the project

> One project contains Java source files that are not compiled (/code/myapplication/module45/sub12)

**Comment by szpak** [comment]
It had turned out that I needed it in the another project and implemented it.
