### ISSUE TITLE
reports

### ISSUE THREAD

**Issue by santi10** [SonarQubeCommunity/sonar-findbugs#69]
Hi,

I'm working with sonarqube v6.1 but I don't get create a report type pdf, xml or html...is it posible??? May you help me, please?

Thx

**Comment by h3xstream** [comment]
Wrong issue tracker. This is not a feature of sonar-findbugs. Please make minimal effort before reporting issue/feature request.

**Comment by santi10** [comment]
Sorry, it was a mistake

Sorry by inconvenience
