### ISSUE TITLE
findbugs-result.xml contents are not shown in SonarQube Project Dashboard

### ISSUE THREAD

**Issue by SagarAdagale** [SonarQubeCommunity/sonar-findbugs#70]
Hi,

I am using Sonar Qube V 6.1 for static java code analysis, going forward i would like to use Sonar Qube for Java code vulnerabilities and security.
For Java code vulnerabilities i have installed FindBugs V 3.4.4 which by default includes FindSecureBug.
I have enabled "FindBugs Security Audit" profile as default

Following entries i have done in my Sonar Project Property File
```
sonar.projectKey=COLLECTIONS_EJB_EOD
sonar.projectName=COLLECTIONS_EJB_EOD_CLASSES
sonar.projectVersion=1.0
sonar.sources=C:/SagarData/sonar-scanner-2.8/SonarProject/COLLECTIONS/indus/coll/ejb/eod
sonar.java.binaries=C:/SagarData/sonar-scanner-2.8/SonarProject/Collections_BinaryCode/indus/coll/ejb/eod
sonar.binaries=C:/SagarData/sonar-scanner-2.8/SonarProject/Collections_BinaryCode
```
Everything goes smooth and i get the "Execution Success" message and my project details are visible in SonarQube Project dashboard

Issue is i can not see the security vulnerabilities which are present in  findbugs-result.xml nor it shows any bug in project dashboard

Regards,
Sagar

**Comment by h3xstream** [comment]
Any warning in the executing of SonarQube command line script? (log would be appreciated)

**Comment by Soneshdabhi** [comment]
Sorry for cross posting, I have same exact issue as mentioned here #80

**Comment by h3xstream** [comment]
The related bug #80 was closed.
If it is related to source folder being named `/source`. If this is not the case, poke me.
