### ISSUE TITLE
Compiled classes in JARs not recognized

### ISSUE THREAD

**Issue by TorstenJ** [SonarQubeCommunity/sonar-findbugs#71]
We have an eclipse RCP setup, most of our java classes are compiled and packed into a jar for each plugin. We can run successfully Findbugs directly on these plugins and now want to switch to sonarqube with findbugs reporting.
Unfortunately the sonar-findbugs wrapper tests if there are *.class files present and ignores the *.jar file, aborting the analysis with an IllegalStateException. As mentioned already running Findbugs directly has no issue with scanning Jars so I think this should be allowed for sonar-findbugs as well.

**Comment by h3xstream** [comment]
You could extract the jars files to the directory `/target/classes` (assuming Maven is used).

**Comment by TorstenJ** [comment]
It is correct that we could unpack the jars manually, we would need to add extra code for this (we are not using maven but pdebuilder).
Still i think this extra hoop to jump through is awkward just to satisfy a test in the sonar plugin, while findbugs itself has no issue with jars. I even wonder why the test was introduced in the first place.
