### ISSUE TITLE
How can i upload findbugs-result.xml to SonarQube WEB or DB?

### ISSUE THREAD

**Issue by gifeel** [SonarQubeCommunity/sonar-findbugs#74]
Hi, I am using Findbugs Plugin 3.3.4 with SonarQube 5.6.4.(with jenkins)
How can i upload findbugs-result.xml to SonarQube WEB or DB?

I did google it a lot. but i couldn't get any more solution about this.
I had finished SonarRunner Setting in jenkins and findbugs Quality Profile Setting in SoanrQube.
And i had written "sonar.java.binaries=.xx/xx" in sonar-project.properties.
so, i got the findbugs-result.xml and could see findbugs-result.xml in jenkins. 
but i couldn't see the findbugs result in SonarQube web.

[my sonar-project.properties]
sonar.projectKey=findbugstest
sonar.projectName=SWE_Findbugs_JAVA
sonar.projectVersion=1.0
sonar.sources=.
sonar.language=java
sonar.sourceEncoding=UTF-8

sonar.java.binaries=./JFoenix-master/bin
sonar.java.libraries=./JFoenix-master/build/dist/*.jar
sonar.findbugs.reportPath=.sonar/findbugs-result.xml

**Comment by gifeel** [comment]
i tried all about this : https://github.com/SonarQubeCommunity/sonar-findbugs/issues/52
but it didn't work.

**Comment by Thg-vinod-anandan** [comment]
You need to create a new "Quality Profile", which also includes the Findbugs rules and make it as "Default".

Alternatively, you can set the Findbugs "Quality Profile" as "Default" 

https://www.youtube.com/watch?v=kzCCZ3RucsQ

**Comment by gifeel** [comment]
thanks your comment.
but i set 'Quality Profile' already, because i tried all about this : #52.

**Comment by Thg-vinod-anandan** [comment]
Could you please let me know how many rules are activated in your "Default" "Quality Profile"?

If it's possible, can you share the screenshot of your "Default" "Quality Profile" and copy your Sonarqube scanner (SonarRunner) logs / Jenkins job logs?

Also, please try to scan without "sonar.findbugs.reportPath=.sonar/findbugs-result.xml" property.

**Comment by KLBonn** [comment]
Maybe just another instance of #51 ?
(because you wrote "sonar.java.binaries=./JFoenix-master/bin", so maybe also your source files live in a non-maven directory layout?)

**Comment by h3xstream** [comment]
SonarQube doesnot allow the import of result. Because of its design having a fix list of rules, plugins tends to embedded the engine it self.
It is the case of this plugin.

**Comment by h3xstream** [comment]
```
How can i upload findbugs-result.xml to SonarQube WEB or DB?
```
You can not run findbugs manually separately. If you need something special, it might be easier to configured the [Jenkins plugin](https://wiki.jenkins-ci.org/display/JENKINS/FindBugs+Plugin).
