### ISSUE TITLE
The class '...' could not be match to its original source file.

### ISSUE THREAD

**Issue by pstibrany** [SonarQubeCommunity/sonar-findbugs#77]
Similar to #51, but we don't use Gradle or Maven. We use command-line scanner, with sources stored in /java-src.

In our sonar-project.properties, we have this:

> sonar.sources=java-src/

Other analysers have no problems with this, but sonar-findbugs complains about being unable to find original source files.

I've tried to fix this by changing FindbugsSensor#findOriginalClassForBug method to use `javaResourceLocator.findSourceFileKeyByClassName`, and that actually helped! Here is the full patch:

```patch
diff --git a/src/main/java/org/sonar/plugins/findbugs/FindbugsSensor.java b/src/main/java/org/sonar/plugins/findbugs/FindbugsSensor.java
index c2174a2..18d8bf8 100644
--- a/src/main/java/org/sonar/plugins/findbugs/FindbugsSensor.java
+++ b/src/main/java/org/sonar/plugins/findbugs/FindbugsSensor.java
@@ -195,20 +195,12 @@ public class FindbugsSensor implements Sensor {
    * @return File handle of the original class file analyzed
    */
   private File findOriginalClassForBug(String className) {
-    String classFile = className.replaceAll("\\.","/").concat(".class");
-
-    for(File classPath : javaResourceLocator.classpath()) {
-      if(!classPath.isDirectory()) {
-        continue;
-      }
-
-      File testClassFile = new File(classPath, classFile);
-      if(testClassFile.exists()) {
-        return testClassFile;
-      }
+    String sourceFile = javaResourceLocator.findSourceFileKeyByClassName(className);
+    if (sourceFile == null) {
+      return null;
     }
 
-    return null;
+    return new File(sourceFile);
   }
 
   @Override
```

Tbh, this is the first time I see sonar plugin code and sonar API, so I have no idea what I'm doing, but tests still pass, and it fixes our problem. Ship it! :)

With this patch, we can now finally see FindBugs issues in our code in SonarQube!

**Comment by h3xstream** [comment]
Cool. I will look at this potential fix.

**Comment by h3xstream** [comment]
@pstibrany Can you do a PR to the project?

**Comment by pstibrany** [comment]
Sure, PR sent. Note that I haven't bumped the version number in this PR.

**Comment by Soneshdabhi** [comment]
Checking if there is an ETA when this will be merged.

**Comment by pstibrany** [comment]
I believe that it has been merged yesterday.
