### ISSUE TITLE
FindBugs Results not publish to SonarQube - Source direction (/source) not detected

### ISSUE THREAD

**Issue by Soneshdabhi** [SonarQubeCommunity/sonar-findbugs#80]
Is there any documentation for how to configure a project properly ? I have following setup and I see no bug reports apart from duplication at end of scan.  Will really appreciate help with this.
```
sonar.projectKey=CRM
sonar.projectName=CRM
sonar.projectVersion=2.5

#Contains all .java files 
sonar.sources=C:\\CRM\\source
#Contains all .class files for folder above
sonar.java.binaries=C:\\CRM\\dist
#Contains all .jar files used in source
sonar.java.libraries=C:\\CRM\\jar

sonar.sourceEncoding=UTF-8
sonar.language=java
```

**Comment by h3xstream** [comment]
I am not using manual configuration myself (with SonarRunner).

Here is the official documentation : https://docs.sonarqube.org/display/PLUG/Java+Plugin+and+Bytecode

**Comment by Soneshdabhi** [comment]
Appreciate your reply. Forgot to reply here that issue I had was resolved. However with Findbugs Ant Task I get lot of following for every single class in the files list, just in case you had any input.

[sonar:sonar] The class 'crm.Event' could not be matched to its original source file. It might be a dynamically generated class.

**Comment by h3xstream** [comment]
With the latest version of SQ API, the property `sonar.sources` is no longer expose to plugin. At the moment, the source folder are "brute force" base on standard project structure (src/, src/main/java , etc.).  It is very limited approach. As an example `/source` is not cover.. 😲
The fix will come at some point #51.

**Comment by Soneshdabhi** [comment]
Great ! One last question , 

When I have "Sonar Way" as default profile my bug report is populated with 4,000 bugs and 800 vulnerabilities. When setting Findbugs as default it shows as 0 bugs and vulnerabilities. Also it looks like it never used security rules from findbugs. Does this mean findbugs rules are not at all loaded when its set as default ?

[findbugs-default.txt](https://github.com/SonarQubeCommunity/sonar-findbugs/files/811444/findbugs-default.txt)
[sonar-default.txt](https://github.com/SonarQubeCommunity/sonar-findbugs/files/811443/sonar-default.txt)



![image](https://cloud.githubusercontent.com/assets/2332457/23470529/9ae039c2-fe74-11e6-96a9-8ed7e37f971d.png)

**Comment by Soneshdabhi** [comment]
Just to provide more information , looks like there is issue with latest installation of sonarqube + findbugs plugin , after completion of the scan I see the result but it doesnt get uploaded to portal. I am checking though to see if I can somehow get the report manually to portal.

**Comment by Soneshdabhi** [comment]
Once I changed structure has to be /src/*.java and bin/*.class report came through fine. So looks like a fix mentioned on another post should fix issue.

**Comment by h3xstream** [comment]
@Soneshdabhi A cleaner fix will be coming in #51 for the source folder discovery.

**Comment by Soneshdabhi** [comment]
Thanks for update , any ETA ?

**Comment by h3xstream** [comment]
@Soneshdabhi Soon
