### ISSUE TITLE
Incompatibility with SQ 6.4 because of code colorizer API

### ISSUE THREAD

**Issue by dbmeneses** [SonarQubeCommunity/sonar-findbugs#84]
The code colorizer API (deprecated since 4.5.2) will be removed in SonarQube 6.4. More details here:
https://jira.sonarsource.com/browse/SONAR-7860

FindBugs plugin is currently still using it, which would make it incompatible with SonarQube 6.4. It should use directly the highlighting mechanism available in the SensorContext.

**Comment by h3xstream** [comment]
@dbmeneses This could be the end of FindBugs support..
Unless SQ is providing a API that is similar..

**Comment by marschall** [comment]
AFAIK this only affects JSP highlighting. How critical is that? Would you be willing to accept a PR that simply removes JSP highlighting?

**Comment by marschall** [comment]
I believe this is fixed #93

**Comment by h3xstream** [comment]
I will try to introduce an alternative in the next release. Otherwise, it may stay black on white for a while.
