### ISSUE TITLE
Lacking FindBugs rules after upgrade

### ISSUE THREAD

**Issue by ymartin59** [SonarQubeCommunity/sonar-findbugs#85]
After a system upgrade to Sonarqube LTS 5.6.6 with FindBugs plugin 3.4.4, a quality profile reports rules have been deactivated because no longer available. But two of them are still available in FindBugs:
- [findbugs:OBL_UNSATISFIED_OBLIGATION_EXCEPTION_EDGE](http://findbugs.sourceforge.net/bugDescriptions.html#OBL_UNSATISFIED_OBLIGATION_EXCEPTION_EDGE)
- [findbugs:LG_LOST_LOGGER_DUE_TO_WEAK_REFERENCE](http://findbugs.sourceforge.net/bugDescriptions.html#LG_LOST_LOGGER_DUE_TO_WEAK_REFERENCE)

![selection_322](https://cloud.githubusercontent.com/assets/2196184/24355509/7b3c77de-12f6-11e7-92aa-5f366b44fa41.png)

What happened with these two FindBugs rules ?

**Comment by marschall** [comment]
To me this looks like a duplicate of #95

**Comment by ymartin59** [comment]
Comparing dates, I would say #95 is a duplicated of mine ;) By the way quality profiles using these ones have to be reconfigured.
