### ISSUE TITLE
Can not execute Findbugs

### ISSUE THREAD

**Issue by edwardzhang121** [SonarQubeCommunity/sonar-findbugs#86]
```
14:18:05.523 WARN  - Findbugs needs sources to be compiled. Please build project before executing sonar or check the location of compiled classes to make it possible for Findbugs to analyse your project.
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
Total time: 7.131s
Final Memory: 14M/170M
INFO: ------------------------------------------------------------------------
ERROR: Error during Sonar runner execution
ERROR: Unable to execute Sonar
ERROR: Caused by: Can not execute Findbugs
ERROR: Caused by: This project contains Java source files that are not compiled.
ERROR: 
ERROR: To see the full stack trace of the errors, re-run SonarQube Runner with the -e switch.
ERROR: Re-run SonarQube Runner using the -X switch to enable full debug logging.
i don't know why ,who can tell me how to fix this.thanks(I use the findbugs version 3.4.4; the sonar version 6.2)
```

**Comment by Soneshdabhi** [comment]
Make sure you are pointing to correct compiled files, for example

#Contains all .java files 
sonar.sources=C:\\Project\\source
#Contains all .class files for folder above
sonar.java.binaries=C:\\Project\\dist
#Contains all .jar files used in source
sonar.java.libraries=C:\\Project\\jar

sonar.sourceEncoding=UTF-8
sonar.language=java

**Comment by h3xstream** [comment]
@edwardzhang121 Please describe you project and folder structure.

**Comment by edwardzhang121** [comment]
hello

执行sonar-runner提示如下




 
From: Sonesh Dabhi
Date: 2017-03-29 23:23
To: SonarQubeCommunity/sonar-findbugs
CC: Edward Zhang; Author
Subject: Re: [SonarQubeCommunity/sonar-findbugs] Can not execute Findbugs (#86)
Make sure you are pointing to correct compiled files, for example
#Contains all .java files
sonar.sources=C:\Project\source
#Contains all .class files for folder above
sonar.java.binaries=C:\Project\dist
#Contains all .jar files used in source
sonar.java.libraries=C:\Project\jar
sonar.sourceEncoding=UTF-8
sonar.language=java

**Comment by h3xstream** [comment]
This will be fix in the next release..
```
sonar.sources=C:\Project\source
```
