### ISSUE TITLE
Upgrade to find-sec-bugs 1.6.0

### ISSUE THREAD

**Issue by kzaikin** [SonarQubeCommunity/sonar-findbugs#88]
Upgrade to find-sec-bugs 1.6.0
See https://github.com/find-sec-bugs/find-sec-bugs/releases/tag/version-1.6.0

**Comment by javixeneize** [comment]
How can this be installed in sonarqube? Doc says that all those fixes are included in findbugs plugin (https://github.com/find-sec-bugs/find-sec-bugs/wiki/Sonar-Qube-Tutorial), but findbugs latest version is from 2016 (3.4.4)

Thanks

**Comment by kzaikin** [comment]
Those findbugs plugins are included
Right now 1.5.0 is referenced in plugin, bug 1.6.0 was released

**Comment by marschall** [comment]
I believe this is fixed by #97

**Comment by kzaikin** [comment]
Yup

**Comment by javixeneize** [comment]
Hi

This is still unclear for me

Doc page says that the latest sonar findbugs version is 3.5which contains findsecbugs 1.5.0

I assume a newer version (3.6) that contains findsecbugs 1.6.0 will be released, isnt it?
